<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <Lesson Condition="'$(Lesson)' == ''">ATMMachineStateDesign</Lesson>
    <StartupObject>LLDWeekend4.Patterns.$(Lesson)Program</StartupObject>
  </PropertyGroup>
</Project>
